## Bot Settings
# The token of your bot
botToken: ""
# The channel of the bot
chatChannel: ""

## Chat Formats
# Minecraft section (This is what displays in minecraft)
# %username% = Discord username
# %message% = Discord message
#
# Discord section (This is what displays in discord)
# %player_username% = Players Username
# %player_nick% = Players Display Name (usually their nickname)
# %player_uuid% = Players UUID
# %message% = Chat message
format:
  minecraft: "&7[&aD&7]&r <%username%> %message%"
  discord: "%player_nick%: %message%"

## First Join, Join and Leave messages
# %username = Minecraft username
firstJoin:
  enabled: true
  color: 16711915
  message: "\uD83C\uDF89 %username% has joined the server for the first time! \uD83C\uDF89"
join:
  enabled: true
  color: 65280
  message: "%username% has joined the server"
leave:
  enabled: true
  color: 16711680
  message: "%username% has left the server"

## Advancements
advancement:
  enabled: true
  color: 16777045
  message: "%username% has made the advancement %advancement%!"

## Linking and Syncing
# If linking is true, the bot will respond to DMs for codes obtained with /discord link
# If syncgroup is true, the bot will sync users groups to relative ones in discord
# If syncnames is true, the bot will sync users nickname/username to relative ones in discord
# The bot will still try sync if linking is false, this allows you to use the bot on multiple small servers
# You will also need to configure the advanced options below these three
linking: true
syncGroups: true
syncUsernames: true

syncing:
  #These are groups to sync (minecraft group name: discord group id)
  groups: {
    "default": "930579786542227488",
    "player": "930579891760541807",
    "regular": "930580013995143252",
    "member": "930580100397797396",
    "elder": "930580215707611206",
    "veteran": "485904549195022351",
    "champion": "666376095725256745",
    "legend": "598617504981450759",
    "nitro": "585542844966633472",
    "respected": "401199394763833344",
    "premium": "401199308394725376",
    "vip": "399902301319593984"
  }

  # The username placeholder to sync.
  username: "%username%"